config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  #devise_for :users, :controllers => { registrations: 'users/registrations' }
  #devise_for :users, path: "auth", :controllers => {sessions: 'sessions', registrations: 'registrations', confirmations: 'confirmations', passwords: 'passwords', omniauth_callbacks: 'omniauth_callbacks'} 
  get "index/index"

  root :to => "index#index"

  post "posts/create" => 'posts#create'
  get "posts/export_post", to: "posts#export_post"

  get "posts/new" => 'posts#new'
  get "posts/index" => 'posts#index'
  get "posts/my_post" => 'posts#my_post'
  get "posts/view_post/:id" => 'posts#view_post'
  get 'posts/:id', to: "posts#edit"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

    def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    if user
      user.provider = auth.provider
      user.uid = auth.uid
      user.save
    else
      user = User.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
    before_action :authenticate_user!
    def showindex
        render html: "<h1>Hola, Rails!</h1>".html_safe
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
    end

    def failure
      redirect_to root_path
    end
 end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:new,:create]
    def new 
        @post = Post.new
    end

    def create 

        id_post=params[:id]
        title = params[:title]
        description = params[:description]
        publication_date = Time.now#.strftime('%F')

        image = nil
        image = save_file(params[:image],'images_post') if id_post.blank?
        @post = Post.new if id_post.blank?
        @post = Post.find(id_post) if !id_post.blank?
        @post.title = title
        @post.description = description
        @post.image_post = image if id_post.blank?
        @post.author = current_user.email
        @post.publication_date = publication_date
        @post.save

        redirect_to '/'
    end
    
    def edit
        id_post=params[:id]
        @post = Post.find(id_post) if !id_post.blank?
    end

    def index
        @post=Post.all
    end

    def my_post
        @post=Post.where('author=?', current_user.email)
    end

    def view_post
        id_post=params[:id]
        @post = Post.find(id_post) if !id_post.blank?
    end

    def export_post
        @post = Post.all
        time=Time.zone.now
        date=time.strftime('%b%d%Y')
        respond_to do |format|
            format.html
    format.xlsx{
        response.headers['Content-Disposition'] = "attachment; filename=All_post_#{date}#{time}.xlsx"
      }
        end
      end

    private

    def save_file(file,folder_img)
            ########SAVE images
            folder = "#{Rails.root}/public/#{folder_img}"
            name_file = (Time.new.to_s+'_'+file.original_filename).gsub(' ','')
            path = File.join(folder, name_file)
            File.open(path, "wb") { |f| f.write(file.read) };
            ################
            path_save = '/'+folder_img+'/'+name_file
            return path_save 
    end
    def delete_file(img)
        img_r="#{img}"
        if !img_r.blank?
          img = "#{Rails.root}/public/#{img}"  
          File.delete(img) if File.exist?(img)
        end
    end

end

app/controllers/read_excel_controller.rb
class ReadExcelController < ApplicationController

	def post_import

		project_id = params[:project_id]
		@project_id = project_id
		#@user = User.find(39)
		#proj_unit_id = 75
		proj_unit_id = params[:proj_unit_id]
		shoot_date = params[:shoot_date] 
		file = params[:file]
		name_file = file.original_filename;
		name_file = name_file.split('.xlsx')
		folder = "#{Rails.root}/public"
		concat = rand(12254)
		valor = concat.to_s
		namefile = name_file[0].to_s+'_'+valor+'.xlsx'
		#Ruta del archivo
		path = File.join(folder, namefile);
		resultado = File.open(path, "wb") { |f| f.write(file.read) };

		require 'spreadsheet'
		open_book = Roo::Spreadsheet.open(path)
		sheet = open_book.sheet(0)
		
		sheet.each_with_index do |sh, idx|
			if !sh[0].blank?
				read_text  = 1 if sh[0].to_s.include? 'CATERING' 
				read_text  = 2 if sh[0].to_s.include? 'Episodio' 
				read_text  = 3 if sh[0].to_s.include? 'CAST' 
				read_text  = 5 if sh[0].to_s.include? 'STUNTS' 
				read_text  = 6 if sh[0].to_s.include? 'EXTRAS' 
				read_text  = 7 if sh[0].to_s.include? 'NOTAS' 


				case read_text
				when 1
					read_food(sh)
					read_location(sh)
				when 2
					read_scenes(sh)
				when 3
					read_cast(sh,nil)
				when 4
					read_cast(sh,10)
				when 5
					read_cast(sh,15)
				when 6
					read_extra(sh)
				when 7
					read_notes(sh)
				end
			end
		end
		####################
		render :json => {
						:shooting_id => @shooting.id,
					}
		FileUtils.rm path
		
	end
	private
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new_post
    
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="username">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="#">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password?</a>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <%= yield %>
    <div id="user_nav">
  <% if user_signed_in? %>
    Conectado como <%= current_user.email %>. isn't that you?
    <%= link_to "Log off", destroy_user_session_path, :method => :delete%>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> o
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</div>
  </body>
</html>

app/views/posts/edit.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<!--<link rel="stylesheet" type="text/css" href="styles.css">-->
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				
			<%= form_tag({:controller => "posts", :action => "create"},:method => "post", :multipart => true, :class =>'') do %>
				<% if !@post.blank? and @post.author != current_user.email %>
				<h1 style="color:#ffffff;" align="center">Acces denied</h1>
				<a href="/" style="color:#ffffff;" >BACK</a>
				<% else %>
					<input type="hidden" name="id" value ="<%= !@post.blank? ?  @post.id : '' %>" >
					<label>Title</label>
					<input type="text" name="title" required="" value="<%= !@post.blank? ?  @post.title : '' %>">
					<br>

					<label>Description</label>
					<input type="textarea" name="description" required="" value="<%= !@post.blank? ?  @post.description : '' %>">
					<br>
					<input type="file" name="image" class="form-control" <% if @post.blank? %> <% end %> >
					<% if !@post.blank? %>
						<img src="<%=@post.image_post %>" width="100" height="100"> 
						<input type="hidden" name="id" value ="<%= @post.id%>" ><br>
					<% end %>
					<input type="submit" value="Guardar" class="login_btn">
				<%end%>
			<%end%>

			</div>
			
		</div>
	</div>
</div>
</body>
</html>

app/views/posts/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<!--<link rel="stylesheet" type="text/css" href="styles.css">-->
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100" align="center">
     <h1>POSTS</h1>
      
            <% @post.each do |posta|%>
           
                  <div class="card" style="padding:15px;max-width:300px">
                    <h3 class="text-upercase"><%=posta.title.upcase%></h3>
                    <p align="center">    <img src="<%=posta.image_post %>" width="200" height="100" align="center"> </p>
                    <p class="text-secondary" ><%=posta.created_at%></p>
                    <%= link_to "See more", "view_post/#{posta.id}" %>
                    <a href="/">BACK</a>
                </div>
            
            <%end%>
         <%= link_to "Export post as spreadsheet", posts_export_post_path(format: "xlsx") %>
       
	</div>
    
</div>
</body>
</html>

app/views/posts/my_post.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<!--<link rel="stylesheet" type="text/css" href="styles.css">-->
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100" align="center">
     <h1>POSTS</h1>
      
            <% @post.each do |posta|%>
           
                  <div class="card" style="padding:15px;max-width:300px">
                    <h3 class="text-upercase"><%=posta.title.upcase%></h3>
                    <p align="center">    <img src="<%=posta.image_post %>" width="200" height="100" align="center"> </p>
                    <p class="text-secondary" ><%=posta.created_at%></p>
                    <%= link_to "Edit", "#{posta.id}" %>
                    <a href="/">BACK</a>
                </div>
            
            <%end%>
       
	</div>
    
</div>
</body>
</html>

app/views/posts/new.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="//maps.google.com/maps/api/js?key=AIzaSyD9UBHQ4rBtr1_B3WgnsyzF7vEB_kX9Z3Q"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
	
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
			<table style="width: 90%;">
			<%= form_tag({:controller => "posts", :action => "create"},:method => "post", :multipart => true, :class =>'') do %>
				
				<tr><h1 style="color:#ffffff;">New Post</h1></tr>
				<tr><p align="center"><img src="<%= asset_path('logo_image.png') %>" width="150" height="100" border="3"></p></tr>
				<tr><input style="border-radius: 10px;" type="file" name="image" width="300" class="form-control"  required="" ></tr>
				<tr>
				<input type="hidden" name="id" value ="<%= !@user_admin.blank? ?  @user_admin.id : '' %>" >
				<td><label style="color:#ffffff;">Title</label></td>
				<td><input style="border-radius: 10px;" type="text" name="title" required="" value="<%= !@user_admin.blank? ?  @user_admin.name : '' %> "></td>
				</tr>
				<br>
				<tr>
				<td><label style="color:#ffffff;">Description</label></td>
				<td><textarea style="border-radius: 10px;" rows="2" cols="30"  name="description"  required="" ></textarea></td>
				<br>
				</tr>
				<tr></tr>
				<tr></tr>
			</table>
			
			<table style="width: 90%;">
			<tr><td width="140"><br><input type="submit" value="Save" class="login_btn"><br></td>
				<td width="140"></td>
				<td><br><input type="submit" onclick="history.back()" value="Back" class="login_btn"><br></td></tr>
  			</table>
			  <%end%>
			</div>
		</div>
	</div>
</div>
</body>
</html>

app/views/posts/view_post.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<!--<link rel="stylesheet" type="text/css" href="styles.css">-->
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100" align="center">
     <h1>POSTS</h1>
      
          
           
                  <div class="card" style="padding:15px;max-width:300px">
                    <h3 class="text-upercase"><%=@post.title.upcase%></h3>
                    <p align="center">    <img src="<%=@post.image_post %>" width="200" height="100" align="center"> </p>
                    <p class="text-secondary" ><%=@post.created_at%></p>
                    
                    <input type="submit" onclick="history.back()" value="Back" class="login_btn"><br></td>
                </div>
            
          
       
	</div>
    
</div>
</body>
</html>